const TYPES = {
  REQUEST_WEATHER: 'REQUEST_WEATHER',
  ADD_WEATHER: 'ADD_WEATHER',
  ERROR_WEATHER: 'ERROR_WEATHER',
  REQUEST_DETAILS: 'REQUEST_DETAILS',
  ADD_DETAILS: 'ADD_DETAILS',
  ERROR_DETAILS: 'ERROR_DETAILS'
}

export default TYPES
